version: '3.8'

services:
  # Frontend Angular Application
  frontend:
    build:
      context: ./gold-trader-ui
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./gold-trader-ui/node_modules:/app/node_modules
    depends_on:
      - trading_app
    networks:
      - gold_trader_network
    restart: unless-stopped